sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: xh997277

  alioss:
    endpoint: oss-cn-nanjing.aliyuncs.com
    access-key-id: LTAI5tLAifvdk9YAR6JQBUEX
    access-key-secret: IOHFuZhz0uuJ3P1AHmSkOldCcmqa3W
    bucket-name: xuhaosky
  redis:
    host: localhost
    port: 6379
    auth: "123456"
    database: 10